version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nestjs
    networks:
      - nestjsnetwork 
  test-db:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nestjs
    networks:
      - nestjsnetwork 
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - nestjsnetwork
networks:
  nestjsnetwork: